import { AccountSideSchema, AccountTypeSchema } from '@shared';
import { AccountSideType as AccountSide } from '@input-type-schemas/AccountSideSchema';
import { AccountTypeType as AccountType } from '@input-type-schemas/AccountTypeSchema';

/**
 * Bir tenant (organization) açılışında kopyalanacak klinik TDHP şablonu.
 * Düz liste; `parentCode` ile ağaç kurulur. Yalnızca yaprak (isPostable=true)
 * hesaplara fiş atılır. Ana/başlık hesaplar isPostable=false.
 *
 * Hesap karakteri (normalSide), TDHP sınıfının genel yönünden farklı olabilen
 * (-) karakterli hesaplarda (103, 256, 257, 580, 591, 610, 611, 7x1 yansıtma)
 * açıkça ters yazılır.
 */
export interface AccountTemplateNode {
  code: string;
  name: string;
  parentCode: string | null;
  type: AccountType;
  normalSide: AccountSide;
  isPostable: boolean;
  requiresParty?: boolean;
}

const { ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE } = AccountTypeSchema.enum;
const { DEBIT, CREDIT } = AccountSideSchema.enum;

export const CLINIC_CHART_OF_ACCOUNTS_TEMPLATE: readonly AccountTemplateNode[] =
  [
    // ─────────────────────────── 1 — Dönen Varlıklar ───────────────────────────
    {
      code: '100',
      name: 'Kasa',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '101',
      name: 'Alınan Çekler',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '102',
      name: 'Bankalar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '103',
      name: 'Verilen Çekler ve Ödeme Emirleri (-)',
      parentCode: null,
      type: ASSET,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '108',
      name: 'Diğer Hazır Değerler (POS)',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '120',
      name: 'Alıcılar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
      requiresParty: true,
    },
    {
      code: '121',
      name: 'Alacak Senetleri',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '126',
      name: 'Verilen Depozito ve Teminatlar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '127',
      name: 'Diğer Ticari Alacaklar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '150',
      name: 'İlk Madde ve Malzeme',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '153',
      name: 'Ticari Mallar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '159',
      name: 'Verilen Sipariş Avansları',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '191',
      name: 'İndirilecek KDV',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '193',
      name: 'Peşin Ödenen Vergiler ve Fonlar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '196',
      name: 'Personel Avansları',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },

    // ─────────────────────────── 2 — Duran Varlıklar ───────────────────────────
    {
      code: '253',
      name: 'Tesis, Makine ve Cihazlar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '254',
      name: 'Taşıtlar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '255',
      name: 'Demirbaşlar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '256',
      name: 'Birikmiş Amortismanlar (-) [253/254]',
      parentCode: null,
      type: ASSET,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '257',
      name: 'Birikmiş Amortismanlar (-) [255]',
      parentCode: null,
      type: ASSET,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '260',
      name: 'Haklar',
      parentCode: null,
      type: ASSET,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '268',
      name: 'Birikmiş Amortismanlar (-) [260]',
      parentCode: null,
      type: ASSET,
      normalSide: CREDIT,
      isPostable: true,
    },

    // ──────────────────── 3 — Kısa Vadeli Yabancı Kaynaklar ─────────────────────
    {
      code: '320',
      name: 'Satıcılar',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
      requiresParty: true,
    },
    {
      code: '321',
      name: 'Borç Senetleri',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '329',
      name: 'Diğer Ticari Borçlar',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '335',
      name: 'Personele Borçlar',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '336',
      name: 'Diğer Çeşitli Borçlar',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '340',
      name: 'Alınan Sipariş Avansları',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
      requiresParty: true,
    },
    {
      code: '360',
      name: 'Ödenecek Vergi ve Fonlar',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '361',
      name: 'Ödenecek Sosyal Güvenlik Kesintileri',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '391',
      name: 'Hesaplanan KDV',
      parentCode: null,
      type: LIABILITY,
      normalSide: CREDIT,
      isPostable: true,
    },

    // ─────────────────────────── 5 — Öz Kaynaklar ──────────────────────────────
    {
      code: '500',
      name: 'Sermaye',
      parentCode: null,
      type: EQUITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '570',
      name: 'Geçmiş Yıllar Kârları',
      parentCode: null,
      type: EQUITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '580',
      name: 'Geçmiş Yıllar Zararları (-)',
      parentCode: null,
      type: EQUITY,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '590',
      name: 'Dönem Net Kârı',
      parentCode: null,
      type: EQUITY,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '591',
      name: 'Dönem Net Zararı (-)',
      parentCode: null,
      type: EQUITY,
      normalSide: DEBIT,
      isPostable: true,
    },

    // ────────────────────── 6 — Gelir Tablosu Hesapları ────────────────────────
    {
      code: '600',
      name: 'Yurtiçi Satışlar',
      parentCode: null,
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: false,
    },
    {
      code: '600.01',
      name: 'Muayene / Kontrol',
      parentCode: '600',
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '600.02',
      name: 'Dolgu / Restoratif',
      parentCode: '600',
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '600.03',
      name: 'Endodonti (Kanal)',
      parentCode: '600',
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '600.04',
      name: 'Cerrahi / İmplant',
      parentCode: '600',
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '600.05',
      name: 'Protez',
      parentCode: '600',
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '600.06',
      name: 'Ortodonti',
      parentCode: '600',
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '600.07',
      name: 'Estetik / Beyazlatma',
      parentCode: '600',
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '601',
      name: 'Yurtdışı Satışlar (Sağlık Turizmi)',
      parentCode: null,
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '602',
      name: 'Diğer Gelirler',
      parentCode: null,
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '610',
      name: 'Satıştan İadeler (-)',
      parentCode: null,
      type: REVENUE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '611',
      name: 'Satış İskontoları (-)',
      parentCode: null,
      type: REVENUE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '642',
      name: 'Faiz Gelirleri',
      parentCode: null,
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '646',
      name: 'Kambiyo Kârları',
      parentCode: null,
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '653',
      name: 'Komisyon Giderleri (POS/Banka)',
      parentCode: null,
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '656',
      name: 'Kambiyo Zararları',
      parentCode: null,
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '689',
      name: 'Diğer Olağandışı Gider ve Zararlar',
      parentCode: null,
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '690',
      name: 'Dönem Kârı veya Zararı',
      parentCode: null,
      type: REVENUE,
      normalSide: CREDIT,
      isPostable: true,
    },

    // ───────────────────── 7 — Maliyet / Gider Hesapları (7/A) ──────────────────
    {
      code: '740',
      name: 'Hizmet Üretim Maliyeti',
      parentCode: null,
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: false,
    },
    {
      code: '740.01',
      name: 'Sarf Malzeme Tüketimi',
      parentCode: '740',
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '740.02',
      name: 'Dış Laboratuvar (Protez/Zirkonyum)',
      parentCode: '740',
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '740.03',
      name: 'Hekim Hakedişi',
      parentCode: '740',
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '740.04',
      name: 'Sterilizasyon / Atık',
      parentCode: '740',
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '741',
      name: 'Hizmet Üretim Maliyeti Yansıtma',
      parentCode: null,
      type: EXPENSE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '760',
      name: 'Pazarlama, Satış ve Dağıtım Giderleri',
      parentCode: null,
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '761',
      name: 'Pazarlama SDG Yansıtma',
      parentCode: null,
      type: EXPENSE,
      normalSide: CREDIT,
      isPostable: true,
    },
    {
      code: '770',
      name: 'Genel Yönetim Giderleri',
      parentCode: null,
      type: EXPENSE,
      normalSide: DEBIT,
      isPostable: true,
    },
    {
      code: '771',
      name: 'Genel Yönetim Giderleri Yansıtma',
      parentCode: null,
      type: EXPENSE,
      normalSide: CREDIT,
      isPostable: true,
    },
  ] as const;
