export enum LogAction {
  ORGANIZATION_CREATE = 'ORGANIZATION_CREATE',
  ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE',
  ORGANIZATION_SOFT_DELETE = 'ORGANIZATION_SOFT_DELETE',

  CLINIC_CREATE = 'CLINIC_CREATE',
  CLINIC_UPDATE = 'CLINIC_UPDATE',
  CLINIC_SOFT_DELETE = 'CLINIC_SOFT_DELETE',

  // Randevu İşlemleri
  APPOINTMENT_CREATE = 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL',
  APPOINTMENT_COMPLETE = 'APPOINTMENT_COMPLETE',

  // AI & n8n Süreçleri
  AI_PROCESS_START = 'AI_PROCESS_START',
  AI_UNCERTAIN = 'AI_UNCERTAIN', // AI ne yapılacağını anlamadı
  AI_ERROR = 'AI_ERROR',

  // Kullanıcı Hareketleri
  USER_LOGIN = 'USER_LOGIN',
  USER_REGISTER = 'USER_REGISTER',
  USER_UPDATE = 'USER_UPDATE',
  USER_REGISTER_FAILED = 'USER_REGISTER_FAILED',
  USER_SEND_PASSWORD_RESET_LINK = 'USER_SEND_PASSWORD_RESET_LINK',
  USER_DELETE = 'USER_DELETE',
  USER_CAPABILITY_GRANTED = 'USER_CAPABILITY_GRANTED',
  USER_CAPABILITY_REVOKED = 'USER_CAPABILITY_REVOKED',

  // Kritik Sistem Olayları
  DB_BACKUP = 'DB_BACKUP',

  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PAYMENT_CANCELLED = 'PAYMENT_CANCELLED',

  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_PAYMENT_FAILED = 'SUBSCRIPTION_PAYMENT_FAILED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',

  INVOICE_ISSUED = 'INVOICE_ISSUED',
  INVOICE_FAILED = 'INVOICE_FAILED',

  POS_TRANSACTION_INITIATED = 'POS_TRANSACTION_INITIATED',
  POS_TRANSACTION_SUCCESS = 'POS_TRANSACTION_SUCCESS',
  POS_TRANSACTION_FAILED = 'POS_TRANSACTION_FAILED',

  META_ADS_ACCOUNT_CONNECTED = 'META_ADS_ACCOUNT_CONNECTED',
  META_ADS_ACCOUNT_DISCONNECTED = 'META_ADS_ACCOUNT_DISCONNECTED',
  META_ADS_LEAD_RECEIVED = 'META_ADS_LEAD_RECEIVED',
  META_ADS_LEAD_MATCHED = 'META_ADS_LEAD_MATCHED',

  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',
  LEAD_CONVERTED = 'LEAD_CONVERTED',
  LEAD_LOST = 'LEAD_LOST',

  INVENTORY_PRODUCT_CREATE = 'INVENTORY_PRODUCT_CREATE',
  INVENTORY_PRODUCT_UPDATE = 'INVENTORY_PRODUCT_UPDATE',
  INVENTORY_PRODUCT_DELETE = 'INVENTORY_PRODUCT_DELETE',
  INVENTORY_SUPPLIER_CREATE = 'INVENTORY_SUPPLIER_CREATE',
  INVENTORY_SUPPLIER_UPDATE = 'INVENTORY_SUPPLIER_UPDATE',
  INVENTORY_STOCK_RECEIVE = 'INVENTORY_STOCK_RECEIVE',
  INVENTORY_STOCK_USAGE = 'INVENTORY_STOCK_USAGE',
  INVENTORY_STOCK_ADJUST = 'INVENTORY_STOCK_ADJUST',
  INVENTORY_STOCK_TRANSFER = 'INVENTORY_STOCK_TRANSFER',

  // İK (HR) İşlemleri
  EMPLOYEE_HIRE = 'EMPLOYEE_HIRE',
  EMPLOYEE_TERMINATE = 'EMPLOYEE_TERMINATE',
  EMPLOYEE_SALARY_CHANGE = 'EMPLOYEE_SALARY_CHANGE',

  // Onam Formu (Consent Form) İşlemleri
  CONSENT_TEMPLATE_CREATE = 'CONSENT_TEMPLATE_CREATE',
  CONSENT_TEMPLATE_UPDATE = 'CONSENT_TEMPLATE_UPDATE',
  CONSENT_TEMPLATE_ARCHIVE = 'CONSENT_TEMPLATE_ARCHIVE',

  // Güvenlik
  ACCESS_DENIED = 'ACCESS_DENIED',
  PATIENT_ACCESS_DENIED = 'PATIENT_ACCESS_DENIED',
}

export enum LogSource {
  WEB = 'WEB',
  MOBILE = 'MOBILE',
  N8N_AI = 'N8N_AI',
  SYSTEM = 'SYSTEM',
}

export enum LogType {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
  SECURITY = 'SECURITY',
}
