export const ENV = {
  ORIGIN: 'ORIGIN',
  PORT: 'PORT',
  DATABASE_URL: 'DATABASE_URL',
  MONGODB_URI: 'MONGODB_URI',
  REDIS_URL: 'REDIS_URL',
  ADMIN_EMAIL: 'ADMIN_EMAIL',
  BETTERSTACK_TOKEN: 'BETTERSTACK_TOKEN',
  //IYZICO
  IYZICO_API_KEY: 'IYZICO_API_KEY',
  IYZICO_SECRET_KEY: 'IYZICO_SECRET_KEY',
  IYZICO_BASE_URL: 'IYZICO_BASE_URL',
  IYZICO_TERMINAL_BASE_URL: 'IYZICO_TERMINAL_BASE_URL',
  // EMAIL
  EMAIL_ADDRESS: 'EMAIL_ADDRESS',
  EMAIL_PASSWORD: 'EMAIL_PASSWORD',
  EMAIL_SMTP_HOST: 'EMAIL_SMTP_HOST',
  EMAIL_SMTP_PORT: 'EMAIL_SMTP_PORT',
  // META
  META_APP_ID: 'META_APP_ID',
  META_APP_SECRET: 'META_APP_SECRET',
  META_WEBHOOK_VERIFY_TOKEN: 'META_WEBHOOK_VERIFY_TOKEN',
  META_OAUTH_REDIRECT_URI: 'META_OAUTH_REDIRECT_URI',
  TOKEN_CIPHER_KEY: 'TOKEN_CIPHER_KEY',
  // WHATSAPP (messaging)
  WHATSAPP_APP_SECRET: 'WHATSAPP_APP_SECRET',
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: 'WHATSAPP_WEBHOOK_VERIFY_TOKEN',
  // HOTEL BEDS
  HOTELBEDS_HOTEL_API_KEY: 'HOTELBEDS_HOTEL_API_KEY',
  HOTELBEDS_HOTEL_SECRET: 'HOTELBEDS_HOTEL_SECRET',
  HOTELBEDS_TRANSFER_API_KEY: 'HOTELBEDS_TRANSFER_API_KEY',
  HOTELBEDS_TRANSFER_SECRET: 'HOTELBEDS_TRANSFER_SECRET',
} as const;

export type EnvConstant = (typeof ENV)[keyof typeof ENV];
