export const ENV = {
  ORIGIN: 'ORIGIN',
  PORT: 'PORT',
  DATABASE_URL: 'DATABASE_URL',
  MONGODB_URI: 'MONGODB_URI',
  REDIS_URL: 'REDIS_URL',
  ADMIN_EMAIL: 'ADMIN_EMAIL',
  BETTERSTACK_TOKEN: 'BETTERSTACK_TOKEN',
  API_BASE_URL: 'API_BASE_URL',
  IYZICO_API_KEY: 'IYZICO_API_KEY',
  IYZICO_SECRET_KEY: 'IYZICO_SECRET_KEY',
  IYZICO_BASE_URL: 'IYZICO_BASE_URL',
  EMAIL_ADDRESS: 'EMAIL_ADDRESS',
  EMAIL_PASSWORD: 'EMAIL_PASSWORD',
  EMAIL_SMTP_HOST: 'EMAIL_SMTP_HOST',
  EMAIL_SMTP_PORT: 'EMAIL_SMTP_PORT',
} as const;

export type EnvConstant = (typeof ENV)[keyof typeof ENV];
