export const ERROR_CODES = {
  APPOINTMENT: {
    NOT_FOUND: 'APPOINTMENT.NOT_FOUND',
    ALREADY_BOOKED: 'APPOINTMENT.ALREADY_BOOKED',
    INVALID_DATE: 'APPOINTMENT.INVALID_DATE',
  },
  PAYMENT: {
    INSUFFICIENT_FUNDS: 'PAYMENT.INSUFFICIENT_FUNDS',
    TIMEOUT: 'PAYMENT.TIMEOUT',
  },
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
