export const ERROR_CODES = {
  ACCOUNTING: {
    TEMPLATE_MISMATCH: 'ACCOUNTING.TEMPLATE_MISMATCH',
    CANNOT_CREATE_CHILD: 'ACCOUNTING.CANNOT_CREATE_CHILD',
    INVALID_NAME: 'ACCOUNTING.INVALID_NAME',
    ACCOUNT_NOT_FOUND: 'ACCOUNTING.ACCOUNT_NOT_FOUND',
  },
  APPOINTMENT: {
    NOT_FOUND: 'APPOINTMENT.NOT_FOUND',
    ALREADY_BOOKED: 'APPOINTMENT.ALREADY_BOOKED',
    INVALID_DATE: 'APPOINTMENT.INVALID_DATE',
    INVALID_CANCELLATION_DATE: 'APPOINTMENT.INVALID_CANCELLATION_DATE',
    INVALID_CANCELLATION_USER: 'APPOINTMENT.INVALID_CANCELLATION_USER',
    INVALID_CANCELLATION_STATUS: 'APPOINTMENT.INVALID_CANCELLATION_STATUS',
  },
  BARCODE: {
    INVALID: 'BARCODE.INVALID',
  },
  BOOKING_PAYMENT: {
    NOT_FOUND: 'BOOKING_PAYMENT.NOT_FOUND',
    LINK_GENERATION_FAILED: 'BOOKING_PAYMENT.LINK_GENERATION_FAILED',
  },
  AUTH: {
    CLINIC_NOT_ASSIGNED: 'AUTH.CLINIC_NOT_ASSIGNED',
    ORGANIZATION_NOT_ASSIGNED: 'AUTH.ORGANIZATION_NOT_ASSIGNED',
  },
  COORDINATES: {
    INVALID_LATITUDE: 'COORDINATES.INVALID_LATITUDE',
    INVALID_LONGITUDE: 'COORDINATES.INVALID_LONGITUDE',
    INVALID_FORMAT: 'COORDINATES.INVALID_FORMAT',
  },
  CURRENCY: {
    INVALID: 'CURRENCY.INVALID',
  },
  DATABASE: {
    CONNECTION_ERROR: 'DATABASE.CONNECTION_ERROR',
  },
  DATE_RANGE: {
    INVALID_ORDER: 'DATE_RANGE.INVALID_ORDER',
    EXPIRED: 'DATE_RANGE.EXPIRED',
  },
  DAY_MINUTE: {
    INVALID_FORMAT: 'DAY_MINUTE.INVALID_FORMAT',
    OUT_OF_RANGE: 'DAY_MINUTE.OUT_OF_RANGE',
    INVALID_TIME_VALUE: 'DAY_MINUTE.INVALID_TIME_VALUE',
  },
  DAY_MINUTE_RANGE: {
    INVALID_RANGE_ORDER: 'DAY_MINUTE_RANGE.INVALID_RANGE_ORDER',
  },
  EMAIL_ADDRESS: {
    INVALID_FORMAT: 'EMAIL_ADDRESS.INVALID_FORMAT',
  },
  FIREBASE_UID: {
    INVALID: 'FIREBASE_UID.INVALID',
  },
  HOTELBEDS_BOOKING: {
    NOT_FOUND: 'HOTELBEDS_BOOKING.NOT_FOUND',
    ALREADY_CANCELLED: 'HOTELBEDS_BOOKING.ALREADY_CANCELLED',
    INVALID_REFERENCE: 'HOTELBEDS_BOOKING.INVALID_REFERENCE',
  },
  HOTELBEDS_TRANSFER: {
    ALREADY_CANCELLED: 'HOTELBEDS_TRANSFER.ALREADY_CANCELLED',
  },
  HTTP: {
    ERROR: 'HTTP.ERROR',
  },
  IMG: {
    INVALID: 'IMG.INVALID',
    INSECURE_PROTOCOL: 'IMG.INSECURE_PROTOCOL',
  },
  INVENTORY: {
    PRODUCT_NOT_FOUND: 'INVENTORY.PRODUCT_NOT_FOUND',
    SUPPLIER_NOT_FOUND: 'INVENTORY.SUPPLIER_NOT_FOUND',
  },
  IYZICO: {
    TRANSACTION_NOT_FOUND: 'IYZICO.TRANSACTION_NOT_FOUND',
    PAYMENT_RECORD_NOT_FOUND: 'IYZICO.PAYMENT_RECORD_NOT_FOUND',
    INSTALLMENT_INFO_FAILED: 'IYZICO.INSTALLMENT_INFO_FAILED',
  },
  LEAD: {
    ALREADY_FINALIZED: 'LEAD.ALREADY_FINALIZED',
    INVALID_STATUS_TRANSITION: 'LEAD.INVALID_STATUS_TRANSITION',
    NOT_FOUND: 'LEAD.NOT_FOUND',
  },
  META_ADS: {
    NOT_FOUND: 'META_ADS.NOT_FOUND',
  },
  MONEY: {
    NOT_POSITIVE: 'MONEY.NOT_POSITIVE',
    INVALID_ALLOCATION_COUNT: 'MONEY.INVALID_ALLOCATION_COUNT',
    INSUFFICIENT_FUNDS: 'MONEY.INSUFFICIENT_FUNDS',
    CURRENCY_MISMATCH: 'MONEY.CURRENCY_MISMATCH',
  },
  ORGANIZATION: {
    NOT_FOUND: 'ORGANIZATION.NOT_FOUND',
  },
  PATIENT: {
    INVALID_PROFILE_DATA: 'PATIENT.INVALID_PROFILE_DATA',
    NOT_FOUND: 'PATIENT.NOT_FOUND',
    PHONE_REQUIRED: 'PATIENT.PHONE_REQUIRED',
    NOT_REGISTERED: 'PATIENT.NOT_REGISTERED',
  },
  PAYMENT: {
    INSUFFICIENT_FUNDS: 'PAYMENT.INSUFFICIENT_FUNDS',
    TIMEOUT: 'PAYMENT.TIMEOUT',
    NOT_FOUND: 'PAYMENT.NOT_FOUND',
    INSTALLMENT_NOT_FOUND: 'PAYMENT.INSTALLMENT_NOT_FOUND',
    COMPLETED_INSTALLMENT_NOT_FOUND: 'PAYMENT.COMPLETED_INSTALLMENT_NOT_FOUND',
    NOT_REFUNDABLE: 'PAYMENT.NOT_REFUNDABLE',
    NOT_CANCELLABLE: 'PAYMENT.NOT_CANCELLABLE',
    INVALID_INSTALLMENT_PLAN: 'PAYMENT.INVALID_INSTALLMENT_PLAN',
    INSTALLMENT_TOTAL_MISMATCH: 'PAYMENT.INSTALLMENT_TOTAL_MISMATCH',
    PROVIDER_FAILED: 'PAYMENT.PROVIDER_FAILED',
  },
  PROVIDER: {
    NOT_FOUND: 'PROVIDER.NOT_FOUND',
    INVALID_OPERATION_MODE: 'PROVIDER.INVALID_OPERATION_MODE',
    ALREADY_DELETED: 'PROVIDER.ALREADY_DELETED',
    NOT_ACCEPTING_EXAMINATION: 'PROVIDER.NOT_ACCEPTING_EXAMINATION',
  },
  PROVIDER_AVAILABILITY: {
    INVALID_BREAK_TIME_CONFIGURATION:
      'PROVIDER_AVAILABILITY.INVALID_BREAK_TIME_CONFIGURATION',
    BREAK_TIME_OUT_OF_RANGE: 'PROVIDER_AVAILABILITY.BREAK_TIME_OUT_OF_RANGE',
  },
  PROVIDER_SHIFT: {
    NOT_FOUND: 'PROVIDER_SHIFT.NOT_FOUND',
    OUT_OF_SHIFT: 'PROVIDER_SHIFT.OUT_OF_SHIFT',
    BREAK_OVERLAP: 'PROVIDER_SHIFT.BREAK_OVERLAP',
    INVALID_BREAK_CONFIGURATION: 'PROVIDER_SHIFT.INVALID_BREAK_CONFIGURATION',
    BREAK_OUT_OF_RANGE: 'PROVIDER_SHIFT.BREAK_OUT_OF_RANGE',
  },
  PATIENT_TREATMENT_PACKAGE: {
    NOT_FOUND: 'PATIENT_TREATMENT_PACKAGE.NOT_FOUND',
    INVALID_STATUS: 'PATIENT_TREATMENT_PACKAGE.INVALID_STATUS',
    INVALID_CANCEL_STATUS: 'PATIENT_TREATMENT_PACKAGE.INVALID_CANCEL_STATUS',
    INVALID_COMPLETION_STATUS:
      'PATIENT_TREATMENT_PACKAGE.INVALID_COMPLETION_STATUS',
    INVALID_RESUME_STATUS: 'PATIENT_TREATMENT_PACKAGE.INVALID_RESUME_STATUS',
    INVALID_BULK_UPDATE: 'PATIENT_TREATMENT_PACKAGE.INVALID_BULK_UPDATE',
  },
  PERIOD: {
    ALREADY_CLOSED: 'PERIOD.ALREADY_CLOSED',
    NOT_FOUND: 'PERIOD.NOT_FOUND',
    ALREADY_EXISTS: 'PERIOD.ALREADY_EXISTS',
    INVALID_LOCK_STATUS: 'PERIOD.INVALID_LOCK_STATUS',
    INVALID_REOPEN_STATUS: 'PERIOD.INVALID_REOPEN_STATUS',
  },
  PHONE: {
    INVALID: 'PHONE.INVALID',
  },
  POS: {
    DEVICE_NOT_FOUND: 'POS.DEVICE_NOT_FOUND',
    TRANSACTION_NOT_FOUND: 'POS.TRANSACTION_NOT_FOUND',
    ORIGINAL_TRANSACTION_NOT_FOUND: 'POS.ORIGINAL_TRANSACTION_NOT_FOUND',
    NOT_REFUNDABLE: 'POS.NOT_REFUNDABLE',
    NOT_VOIDABLE: 'POS.NOT_VOIDABLE',
    MISSING_EXTERNAL_REF: 'POS.MISSING_EXTERNAL_REF',
    REFUND_AMOUNT_EXCEEDS_ORIGINAL: 'POS.REFUND_AMOUNT_EXCEEDS_ORIGINAL',
    PROVIDER_MISMATCH: 'POS.PROVIDER_MISMATCH',
    MISSING_DEVICE_UNIQUE_ID: 'POS.MISSING_DEVICE_UNIQUE_ID',
    IYZICO_TERMINAL_CONFIG_NOT_FOUND: 'POS.IYZICO_TERMINAL_CONFIG_NOT_FOUND',
    MISSING_PAYMENT_DATE: 'POS.MISSING_PAYMENT_DATE',
  },
  QUANTITY: {
    NEGATIVE: 'QUANTITY.NEGATIVE',
    NOT_GREATER_THAN_ZERO: 'QUANTITY.NOT_GREATER_THAN_ZERO',
    INSUFFICIENT: 'QUANTITY.INSUFFICIENT',
  },
  SHARED: {
    TIME_CONFLICT: 'SHARED.TIME_CONFLICT',
  },
  SLUG: {
    EMPTY: 'SLUG.EMPTY',
  },
  STOCK_CODE: {
    INVALID: 'STOCK_CODE.INVALID',
  },
  TCKN: {
    INVALID_FORMAT: 'TCKN.INVALID_FORMAT',
    INVALID_CHECKSUM: 'TCKN.INVALID_CHECKSUM',
  },
  TIMEZONE: {
    INVALID: 'TIMEZONE.INVALID',
  },
  TREATMENT_PACKAGE: {
    NOT_FOUND: 'TREATMENT_PACKAGE.NOT_FOUND',
    PACKAGE_NAME_EMPTY: 'TREATMENT_PACKAGE.PACKAGE_NAME_EMPTY',
    PACKAGE_PRICE_NEGATIVE: 'TREATMENT_PACKAGE.PACKAGE_PRICE_NEGATIVE',
    PACKAGE_ALREADY_DELETED: 'TREATMENT_PACKAGE.PACKAGE_ALREADY_DELETED',
  },
  USER: {
    INVALID_UPDATE: 'USER.INVALID_UPDATE',
    INVALID_DELETION: 'USER.INVALID_DELETION',
    NOT_FOUND: 'USER.NOT_FOUND',
  },
  UUID: {
    INVALID: 'UUID.INVALID',
  },
  VALIDATION: {
    FAILED: 'FAILED',
  },
  VAT: {
    NEGATIVE: 'VAT.NEGATIVE',
    INVALID_RATE: 'VAT.INVALID_RATE',
    MUST_NOT_BE_ZERO: 'VAT.MUST_NOT_BE_ZERO',
  },
  VKN: {
    INVALID_FORMAT: 'VKN.INVALID_FORMAT',
    INVALID_CHECKSUM: 'VKN.INVALID_CHECKSUM',
  },
} as const;

type ErrorCodeGroups = typeof ERROR_CODES;

/**
 * Tüm grupların yaprak (leaf) kod string'lerinin birleşimi:
 * 'APPOINTMENT.NOT_FOUND' | 'PAYMENT.TIMEOUT' | 'HTTP.ERROR' | ...
 * (Eski tanım grupların kendisini — `{ NOT_FOUND: ... }` — döndürüyordu; iki kademeli index gerekli.)
 */
export type ErrorCode = {
  [Group in keyof ErrorCodeGroups]: ErrorCodeGroups[Group][keyof ErrorCodeGroups[Group]];
}[keyof ErrorCodeGroups];
