const BASE_PATHS = {
  ORGANIZATIONS: 'organizations',
  CLINICS: 'clinics',
  USERS: 'users',
  POS: 'pos',
  PAYMENTS: 'payments',
  IYZICO: 'iyzico',
  CALLBACK: 'callback',
  SUBSCRIPTIONS: 'subscriptions',
  HEALTH_TOURISM: 'health-tourism',
  BOOKING_PAYMENTS: 'booking-payments',
  STRIPE: 'stripe',
  WEBHOOK: 'webhook',
} as const;

export const ROUTE_PATHS = {
  ORGANIZATIONS: BASE_PATHS.ORGANIZATIONS,
  CLINICS: BASE_PATHS.CLINICS,
  USERS: BASE_PATHS.USERS,
  PAYMENTS: {
    ROOT: BASE_PATHS.PAYMENTS,
    IYZICO: {
      ROOT: BASE_PATHS.IYZICO,
      CALLBACK: BASE_PATHS.CALLBACK,
      FULL_CALLBACK_PATH: `${BASE_PATHS.POS}/${BASE_PATHS.IYZICO}/${BASE_PATHS.CALLBACK}`,
    },
  },
  SUBSCRIPTIONS: {
    ROOT: BASE_PATHS.SUBSCRIPTIONS,
    CALLBACK: BASE_PATHS.CALLBACK,
    FULL_CALLBACK_PATH: `${BASE_PATHS.SUBSCRIPTIONS}/${BASE_PATHS.CALLBACK}`,
  },
  // Sağlık turizmi (otel/transfer) ödeme-önce tahsilatı — iyzico callback + Stripe webhook
  BOOKING_PAYMENTS: {
    ROOT: `${BASE_PATHS.HEALTH_TOURISM}/${BASE_PATHS.BOOKING_PAYMENTS}`,
    IYZICO_ROOT: `${BASE_PATHS.HEALTH_TOURISM}/${BASE_PATHS.BOOKING_PAYMENTS}/${BASE_PATHS.IYZICO}`,
    STRIPE_ROOT: `${BASE_PATHS.HEALTH_TOURISM}/${BASE_PATHS.BOOKING_PAYMENTS}/${BASE_PATHS.STRIPE}`,
    CALLBACK: BASE_PATHS.CALLBACK,
    WEBHOOK: BASE_PATHS.WEBHOOK,
    IYZICO_FULL_CALLBACK_PATH: `${BASE_PATHS.HEALTH_TOURISM}/${BASE_PATHS.BOOKING_PAYMENTS}/${BASE_PATHS.IYZICO}/${BASE_PATHS.CALLBACK}`,
    STRIPE_FULL_WEBHOOK_PATH: `${BASE_PATHS.HEALTH_TOURISM}/${BASE_PATHS.BOOKING_PAYMENTS}/${BASE_PATHS.STRIPE}/${BASE_PATHS.WEBHOOK}`,
  },
} as const;

export type RoutePaths = typeof ROUTE_PATHS;
