const BASE_PATHS = {
  ORGANIZATIONS: 'organizations',
  CLINICS: 'clinics',
  USERS: 'users',
  POS: 'pos',
  PAYMENTS: 'payments',
  IYZICO: 'iyzico',
  CALLBACK: 'callback',
  SUBSCRIPTIONS: 'subscriptions',
} as const;

export const ROUTE_PATHS = {
  ORGANIZATIONS: BASE_PATHS.ORGANIZATIONS,
  CLINICS: BASE_PATHS.CLINICS,
  USERS: BASE_PATHS.USERS,
  PAYMENTS: {
    ROOT: BASE_PATHS.PAYMENTS,
    IYZICO: {
      ROOT: BASE_PATHS.IYZICO,
      CALLBACK: BASE_PATHS.CALLBACK,
      FULL_CALLBACK_PATH: `${BASE_PATHS.POS}/${BASE_PATHS.IYZICO}/${BASE_PATHS.CALLBACK}`,
    },
  },
  SUBSCRIPTIONS: {
    ROOT: BASE_PATHS.SUBSCRIPTIONS,
    CALLBACK: BASE_PATHS.CALLBACK,
    FULL_CALLBACK_PATH: `${BASE_PATHS.SUBSCRIPTIONS}/${BASE_PATHS.CALLBACK}`,
  },
} as const;

export type RoutePaths = typeof ROUTE_PATHS;
