export const APPOINTMENT_EVENTS = {
  BOOKED: 'appointment.booked',
  CONFIRMED: 'appointment.confirmed',
  CANCELLED: 'appointment.cancelled',
  COMPLETED: 'appointment.completed',
  NO_SHOW: 'appointment.no_show',
  LIST_CLINIC: 'appointment.list-clinic',
  LIST_ORGANIZATION: 'appointment.list-organization',
  PROVIDER_CALENDAR: 'appointment.provider-calendar',
  FULL_CALENDAR: 'appointment.full-calendar',
  PROVIDER_AVAILABILITY: 'appointment.provider-availability',
  DETAIL: 'appointment.detail',
  ACTION_REQUIRED: 'appointment.action-required',
  SEARCH: 'appointment.search',
  UPCOMING_REMINDERS: 'appointment.upcoming-reminders',
  DAILY_SUMMARY: 'appointment.daily-summary',
  SCHEDULE: 'appointment.schedule',
  SCHEDULED: 'appointment.scheduled',
  CANCELLATION_REQUESTED: 'appointment.cancellation-requested',
  RESCHEDULE: 'appointment.reschedule',
  RESCHEDULED: 'appointment.rescheduled',
  DETAILS_UPDATED: 'appointment.details-updated',
  DETAILS_UPDATE: 'appointment.details-update',
  CHECKED_IN: 'appointment.checked-in',
  CHECK_IN: 'appointment.check-in',
  WAITING_ROOM: 'appointment.waiting-room',
  REMINDER_DUE: 'appointment.reminder-due',
  PROCESS_REMINDERS: 'appointment.process-reminders',
  BULK_SOFT_DELETED: 'appointment.bulk-soft-deleted',
  BULK_CANCELLED: 'appointment.bulk-cancelled',
  CANCEL_PROVIDER_DAY: 'appointment.cancel-provider-day',
  CHECK_CONFLICTS: 'appointment.check-conflicts',
} as const;

export type AppointmentEvent =
  (typeof APPOINTMENT_EVENTS)[keyof typeof APPOINTMENT_EVENTS];
