export const ERROR_CODES = {
  COMMON: {
    CONCURRENCY_CONFLICT: 'COMMON.CONCURRENCY_CONFLICT',
    LOCK_TARGET_MISSING: 'COMMON.LOCK_TARGET_MISSING',
    CLINIC_SCOPE_REQUIRED: 'COMMON.CLINIC_SCOPE_REQUIRED',
  },
  MESSAGING: {
    SERVICE_WINDOW_CLOSED: 'MESSAGING.SERVICE_WINDOW_CLOSED',
    CLINIC_ACCESS_DENIED: 'MESSAGING.CLINIC_ACCESS_DENIED',
    CONVERSATION_NOT_FOUND: 'MESSAGING.CONVERSATION_NOT_FOUND',
    MESSAGE_NOT_FOUND: 'MESSAGING.MESSAGE_NOT_FOUND',
    MARKETING_OPT_OUT: 'MESSAGING.MARKETING_OPT_OUT',
    CHANNEL_NOT_CONNECTED: 'MESSAGING.CHANNEL_NOT_CONNECTED',
    AI_AGENT_CONFIG_NOT_FOUND: 'MESSAGING.AI_AGENT_CONFIG_NOT_FOUND',
  },
  ACTIVITY: {
    NOT_FOUND: 'ACTIVITY.NOT_FOUND',
    INVALID_COMPLETION: 'ACTIVITY.INVALID_COMPLETION',
  },
  PRIORITY: {
    INVALID: 'PRIORITY.INVALID',
  },
  PIPELINE: {
    NOT_FOUND: 'PIPELINE.NOT_FOUND',
    STAGE_NOT_FOUND: 'PIPELINE.STAGE_NOT_FOUND',
  },
  ACCOUNTING: {
    TEMPLATE_MISMATCH: 'ACCOUNTING.TEMPLATE_MISMATCH',
    CANNOT_CREATE_CHILD: 'ACCOUNTING.CANNOT_CREATE_CHILD',
    INVALID_NAME: 'ACCOUNTING.INVALID_NAME',
    ACCOUNT_NOT_FOUND: 'ACCOUNTING.ACCOUNT_NOT_FOUND',
  },
  APPOINTMENT: {
    INVALID_TIME_RANGE: 'APPOINTMENT.INVALID_TIME_RANGE',
    NOT_FOUND: 'APPOINTMENT.NOT_FOUND',
    PATIENT_PHONE_REQUIRED: 'APPOINTMENT.PATIENT_PHONE_REQUIRED',
    ALREADY_BOOKED: 'APPOINTMENT.ALREADY_BOOKED',
    CANNOT_COMPLETE: 'APPOINTMENT.CANNOT_COMPLETE',
    INVALID_DATE: 'APPOINTMENT.INVALID_DATE',
    INVALID_DATE_IN_PAST: 'APPOINTMENT.INVALID_DATE_IN_PAST',
    INVALID_CREATION_DATE: 'APPOINTMENT.INVALID_CREATION_DATE',
    INVALID_CANCELLATION_DATE: 'APPOINTMENT.INVALID_CANCELLATION_DATE',
    INVALID_CANCELLATION_USER: 'APPOINTMENT.INVALID_CANCELLATION_USER',
    INVALID_CANCELLATION_STATUS: 'APPOINTMENT.INVALID_CANCELLATION_STATUS',
    INVALID_RESCHEDULE_STATUS: 'APPOINTMENT.INVALID_RESCHEDULE_STATUS',
    INVALID_NO_SHOW_STATUS: 'APPOINTMENT.INVALID_NO_SHOW_STATUS',
    INVALID_END_DATE: 'APPOINTMENT.INVALID_END_DATE',
    INVALID_START_DATE: 'APPOINTMENT.INVALID_START_DATE',
    ONLY_PENDING_CAN_BE_CONFIRMED: 'APPOINTMENT.ONLY_PENDING_CAN_BE_CONFIRMED',
    NOT_CANCELLED: 'APPOINTMENT.NOT_CANCELLED',
    NOT_COMPLETED: 'APPOINTMENT.NOT_COMPLETED',
    NOT_CONFIRMED: 'APPOINTMENT.NOT_CONFIRMED',
    NOT_PENDING: 'APPOINTMENT.NOT_PENDING',
    NOT_NO_SHOW: 'APPOINTMENT.NOT_NO_SHOW',
    PATIENT_BOOKING_DISABLED: 'APPOINTMENT.PATIENT_BOOKING_DISABLED',
    CLINIC_OUTSIDE_ORGANIZATION: 'APPOINTMENT.CLINIC_OUTSIDE_ORGANIZATION',
    PATIENT_CANCEL_DISABLED: 'APPOINTMENT.PATIENT_CANCEL_DISABLED',
    PATIENT_REQUIRED: 'APPOINTMENT.PATIENT_REQUIRED',
    RESCHEDULE_WINDOW_EXPIRED: 'APPOINTMENT.RESCHEDULE_WINDOW_EXPIRED',
    BOOKING_WINDOW_EXCEEDED: 'APPOINTMENT.BOOKING_WINDOW_EXCEEDED',
    MAX_ACTIVE_BOOKINGS_EXCEEDED: 'APPOINTMENT.MAX_ACTIVE_BOOKINGS_EXCEEDED',
    CHECK_IN_NOT_ALLOWED: 'APPOINTMENT.CHECK_IN_NOT_ALLOWED',
    SLOT_TEMPORARILY_HELD: 'APPOINTMENT.SLOT_TEMPORARILY_HELD',
  },
  BARCODE: {
    INVALID: 'BARCODE.INVALID',
  },
  NOTIFICATION: {
    NOT_FOUND: 'NOTIFICATION.NOT_FOUND',
  },
  BOOKING_PAYMENT: {
    NOT_FOUND: 'BOOKING_PAYMENT.NOT_FOUND',
    LINK_GENERATION_FAILED: 'BOOKING_PAYMENT.LINK_GENERATION_FAILED',
    MANUAL_OVERRIDE_REQUIRED: 'BOOKING_PAYMENT.MANUAL_OVERRIDE_REQUIRED',
  },
  AUTH: {
    CLINIC_NOT_ASSIGNED: 'AUTH.CLINIC_NOT_ASSIGNED',
    ORGANIZATION_NOT_ASSIGNED: 'AUTH.ORGANIZATION_NOT_ASSIGNED',
  },
  CLINIC: {
    NOT_FOUND: 'CLINIC.NOT_FOUND',
    TENANT_SCOPE_MISMATCH: 'CLINIC.TENANT_SCOPE_MISMATCH',
    CLOSED_ON_DATE: 'CLINIC.CLOSED_ON_DATE',
    NOT_WORKING_DAY: 'CLINIC.NOT_WORKING_DAY',
    OUTSIDE_WORKING_HOURS: 'CLINIC.OUTSIDE_WORKING_HOURS',
  },
  COORDINATES: {
    INVALID_LATITUDE: 'COORDINATES.INVALID_LATITUDE',
    INVALID_LONGITUDE: 'COORDINATES.INVALID_LONGITUDE',
    INVALID_FORMAT: 'COORDINATES.INVALID_FORMAT',
  },
  CURRENCY: {
    INVALID: 'CURRENCY.INVALID',
  },
  DATABASE: {
    CONNECTION_ERROR: 'DATABASE.CONNECTION_ERROR',
    VALIDATION_ERROR: 'DATABASE.VALIDATION_ERROR',
  },
  DATE_RANGE: {
    INVALID_ORDER: 'DATE_RANGE.INVALID_ORDER',
    EXPIRED: 'DATE_RANGE.EXPIRED',
  },
  DAY_MINUTE: {
    INVALID_FORMAT: 'DAY_MINUTE.INVALID_FORMAT',
    OUT_OF_RANGE: 'DAY_MINUTE.OUT_OF_RANGE',
    INVALID_TIME_VALUE: 'DAY_MINUTE.INVALID_TIME_VALUE',
  },
  DAY_MINUTE_RANGE: {
    INVALID_RANGE_ORDER: 'DAY_MINUTE_RANGE.INVALID_RANGE_ORDER',
  },
  EMAIL_ADDRESS: {
    INVALID_FORMAT: 'EMAIL_ADDRESS.INVALID_FORMAT',
  },
  FIREBASE_UID: {
    INVALID: 'FIREBASE_UID.INVALID',
  },
  HOTELBEDS_BOOKING: {
    NOT_FOUND: 'HOTELBEDS_BOOKING.NOT_FOUND',
    ALREADY_CANCELLED: 'HOTELBEDS_BOOKING.ALREADY_CANCELLED',
    INVALID_REFERENCE: 'HOTELBEDS_BOOKING.INVALID_REFERENCE',
    INVALID_DATE_RANGE: 'HOTELBEDS_BOOKING.INVALID_DATE_RANGE',
  },
  HOTELBEDS_TRANSFER: {
    ALREADY_CANCELLED: 'HOTELBEDS_TRANSFER.ALREADY_CANCELLED',
  },
  HTTP: {
    ERROR: 'HTTP.ERROR',
  },
  IMG: {
    INVALID: 'IMG.INVALID',
    INSECURE_PROTOCOL: 'IMG.INSECURE_PROTOCOL',
  },
  INVENTORY: {
    PRODUCT_NOT_FOUND: 'INVENTORY.PRODUCT_NOT_FOUND',
    SUPPLIER_NOT_FOUND: 'INVENTORY.SUPPLIER_NOT_FOUND',
  },
  IYZICO: {
    TRANSACTION_NOT_FOUND: 'IYZICO.TRANSACTION_NOT_FOUND',
    PAYMENT_RECORD_NOT_FOUND: 'IYZICO.PAYMENT_RECORD_NOT_FOUND',
    INSTALLMENT_INFO_FAILED: 'IYZICO.INSTALLMENT_INFO_FAILED',
  },
  LAST_NAME: {
    INVALID: 'LAST_NAME.INVALID',
  },
  LEAD: {
    ALREADY_FINALIZED: 'LEAD.ALREADY_FINALIZED',
    INVALID_STATUS_TRANSITION: 'LEAD.INVALID_STATUS_TRANSITION',
    NOT_FOUND: 'LEAD.NOT_FOUND',
    CONVERT_MISSING_TARGET: 'LEAD.CONVERT_MISSING_TARGET',
  },
  META_ADS: {
    NOT_FOUND: 'META_ADS.NOT_FOUND',
  },
  MONEY: {
    NOT_POSITIVE: 'MONEY.NOT_POSITIVE',
    INVALID_ALLOCATION_COUNT: 'MONEY.INVALID_ALLOCATION_COUNT',
    INSUFFICIENT_FUNDS: 'MONEY.INSUFFICIENT_FUNDS',
    CURRENCY_MISMATCH: 'MONEY.CURRENCY_MISMATCH',
  },
  NAME: {
    INVALID: 'NAME.INVALID',
  },
  FULL_NAME: {
    INVALID: 'FULL_NAME.INVALID',
  },
  ORGANIZATION: {
    NOT_FOUND: 'ORGANIZATION.NOT_FOUND',
  },
  PARTY: {
    NOT_FOUND: 'PARTY.NOT_FOUND',
  },
  PATIENT: {
    INVALID_PROFILE_DATA: 'PATIENT.INVALID_PROFILE_DATA',
    NOT_FOUND: 'PATIENT.NOT_FOUND',
    PHONE_REQUIRED: 'PATIENT.PHONE_REQUIRED',
    NOT_REGISTERED: 'PATIENT.NOT_REGISTERED',
    ACCESS_DENIED: 'PATIENT.ACCESS_DENIED',
    CONTACT_REQUIRED: 'PATIENT.CONTACT_REQUIRED',
  },
  PAYMENT: {
    INSUFFICIENT_FUNDS: 'PAYMENT.INSUFFICIENT_FUNDS',
    TIMEOUT: 'PAYMENT.TIMEOUT',
    NOT_FOUND: 'PAYMENT.NOT_FOUND',
    INSTALLMENT_NOT_FOUND: 'PAYMENT.INSTALLMENT_NOT_FOUND',
    COMPLETED_INSTALLMENT_NOT_FOUND: 'PAYMENT.COMPLETED_INSTALLMENT_NOT_FOUND',
    NOT_REFUNDABLE: 'PAYMENT.NOT_REFUNDABLE',
    AMOUNT_UNRESOLVABLE: 'PAYMENT.AMOUNT_UNRESOLVABLE',
    NOT_CANCELLABLE: 'PAYMENT.NOT_CANCELLABLE',
    INVALID_INSTALLMENT_PLAN: 'PAYMENT.INVALID_INSTALLMENT_PLAN',
    INSTALLMENT_TOTAL_MISMATCH: 'PAYMENT.INSTALLMENT_TOTAL_MISMATCH',
    PROVIDER_FAILED: 'PAYMENT.PROVIDER_FAILED',
  },
  PROVIDER: {
    NOT_FOUND: 'PROVIDER.NOT_FOUND',
    INVALID_OPERATION_MODE: 'PROVIDER.INVALID_OPERATION_MODE',
    ALREADY_DELETED: 'PROVIDER.ALREADY_DELETED',
    NOT_ACCEPTING_EXAMINATION: 'PROVIDER.NOT_ACCEPTING_EXAMINATION',
  },
  PROVIDER_AVAILABILITY: {
    INVALID_BREAK_TIME_CONFIGURATION:
      'PROVIDER_AVAILABILITY.INVALID_BREAK_TIME_CONFIGURATION',
    BREAK_TIME_OUT_OF_RANGE: 'PROVIDER_AVAILABILITY.BREAK_TIME_OUT_OF_RANGE',
  },
  PROVIDER_SHIFT: {
    NOT_FOUND: 'PROVIDER_SHIFT.NOT_FOUND',
    OUT_OF_SHIFT: 'PROVIDER_SHIFT.OUT_OF_SHIFT',
    BREAK_OVERLAP: 'PROVIDER_SHIFT.BREAK_OVERLAP',
    INVALID_BREAK_CONFIGURATION: 'PROVIDER_SHIFT.INVALID_BREAK_CONFIGURATION',
    BREAK_OUT_OF_RANGE: 'PROVIDER_SHIFT.BREAK_OUT_OF_RANGE',
  },
  PATIENT_TREATMENT_PACKAGE: {
    NOT_FOUND: 'PATIENT_TREATMENT_PACKAGE.NOT_FOUND',
    INVALID_STATUS: 'PATIENT_TREATMENT_PACKAGE.INVALID_STATUS',
    INVALID_CANCEL_STATUS: 'PATIENT_TREATMENT_PACKAGE.INVALID_CANCEL_STATUS',
    INVALID_COMPLETION_STATUS:
      'PATIENT_TREATMENT_PACKAGE.INVALID_COMPLETION_STATUS',
    INVALID_RESUME_STATUS: 'PATIENT_TREATMENT_PACKAGE.INVALID_RESUME_STATUS',
    INVALID_BULK_UPDATE: 'PATIENT_TREATMENT_PACKAGE.INVALID_BULK_UPDATE',
  },
  PERIOD: {
    ALREADY_CLOSED: 'PERIOD.ALREADY_CLOSED',
    NOT_FOUND: 'PERIOD.NOT_FOUND',
    ALREADY_EXISTS: 'PERIOD.ALREADY_EXISTS',
    INVALID_LOCK_STATUS: 'PERIOD.INVALID_LOCK_STATUS',
    INVALID_REOPEN_STATUS: 'PERIOD.INVALID_REOPEN_STATUS',
    INVALID_YEAR: 'PERIOD.INVALID_YEAR',
  },
  PHONE: {
    INVALID: 'PHONE.INVALID',
  },
  POS: {
    DEVICE_NOT_FOUND: 'POS.DEVICE_NOT_FOUND',
    DEVICE_CLINIC_MISMATCH: 'POS.DEVICE_CLINIC_MISMATCH',
    DEVICE_INACTIVE: 'POS.DEVICE_INACTIVE',
    TRANSACTION_CLINIC_MISMATCH: 'POS.TRANSACTION_CLINIC_MISMATCH',
    TRANSACTION_ALREADY_SETTLED: 'POS.TRANSACTION_ALREADY_SETTLED',
    TRANSACTION_NOT_FOUND: 'POS.TRANSACTION_NOT_FOUND',
    ORIGINAL_TRANSACTION_NOT_FOUND: 'POS.ORIGINAL_TRANSACTION_NOT_FOUND',
    NOT_REFUNDABLE: 'POS.NOT_REFUNDABLE',
    NOT_VOIDABLE: 'POS.NOT_VOIDABLE',
    ALREADY_REVERSED: 'POS.ALREADY_REVERSED',
    REVERSAL_REQUIRES_ORIGINAL: 'POS.REVERSAL_REQUIRES_ORIGINAL',
    MISSING_EXTERNAL_REF: 'POS.MISSING_EXTERNAL_REF',
    REFUND_AMOUNT_EXCEEDS_ORIGINAL: 'POS.REFUND_AMOUNT_EXCEEDS_ORIGINAL',
    PROVIDER_MISMATCH: 'POS.PROVIDER_MISMATCH',
    MISSING_DEVICE_UNIQUE_ID: 'POS.MISSING_DEVICE_UNIQUE_ID',
    IYZICO_TERMINAL_CONFIG_NOT_FOUND: 'POS.IYZICO_TERMINAL_CONFIG_NOT_FOUND',
    MISSING_PAYMENT_DATE: 'POS.MISSING_PAYMENT_DATE',
  },
  REGISTRATION: {
    NOT_COMPLETED: 'REGISTRATION.NOT_COMPLETED',
  },
  QUANTITY: {
    NEGATIVE: 'QUANTITY.NEGATIVE',
    NOT_GREATER_THAN_ZERO: 'QUANTITY.NOT_GREATER_THAN_ZERO',
    INSUFFICIENT: 'QUANTITY.INSUFFICIENT',
  },
  SHARED: {
    TIME_CONFLICT: 'SHARED.TIME_CONFLICT',
  },
  SLUG: {
    EMPTY: 'SLUG.EMPTY',
  },
  STOCK_CODE: {
    INVALID: 'STOCK_CODE.INVALID',
  },
  TCKN: {
    INVALID_FORMAT: 'TCKN.INVALID_FORMAT',
    INVALID_CHECKSUM: 'TCKN.INVALID_CHECKSUM',
  },
  TIMEZONE: {
    INVALID: 'TIMEZONE.INVALID',
  },
  INVOICE: {
    DUPLICATE: 'INVOICE.DUPLICATE',
  },
  TREATMENT_CHARGE: {
    NOT_FOUND: 'TREATMENT_CHARGE.NOT_FOUND',
    LIST_PRICE_MISSING: 'TREATMENT_CHARGE.LIST_PRICE_MISSING',
    DISCOUNT_LIMIT_EXCEEDED: 'TREATMENT_CHARGE.DISCOUNT_LIMIT_EXCEEDED',
    ALREADY_VOIDED: 'TREATMENT_CHARGE.ALREADY_VOIDED',
    ALREADY_INVOICED: 'TREATMENT_CHARGE.ALREADY_INVOICED',
    MIXED_VAT_RATE: 'TREATMENT_CHARGE.MIXED_VAT_RATE',
    CURRENCY_MISMATCH: 'TREATMENT_CHARGE.CURRENCY_MISMATCH',
    NO_CHARGES: 'TREATMENT_CHARGE.NO_CHARGES',
  },
  TREATMENT_PACKAGE: {
    NOT_FOUND: 'TREATMENT_PACKAGE.NOT_FOUND',
    PACKAGE_NAME_EMPTY: 'TREATMENT_PACKAGE.PACKAGE_NAME_EMPTY',
    PACKAGE_PRICE_NEGATIVE: 'TREATMENT_PACKAGE.PACKAGE_PRICE_NEGATIVE',
    PACKAGE_ALREADY_DELETED: 'TREATMENT_PACKAGE.PACKAGE_ALREADY_DELETED',
  },
  USER: {
    INVALID_UPDATE: 'USER.INVALID_UPDATE',
    INVALID_DELETION: 'USER.INVALID_DELETION',
    NOT_FOUND: 'USER.NOT_FOUND',
    CAPABILITY_NOT_FOUND: 'USER.CAPABILITY_NOT_FOUND',
    CAPABILITY_PLATFORM_SCOPED: 'USER.CAPABILITY_PLATFORM_SCOPED',
    CAPABILITY_NOT_HELD_BY_ACTOR: 'USER.CAPABILITY_NOT_HELD_BY_ACTOR',
    CAPABILITY_ALREADY_IN_ROLE: 'USER.CAPABILITY_ALREADY_IN_ROLE',
  },
  UUID: {
    INVALID: 'UUID.INVALID',
  },
  JOURNAL_ENTRY: {
    UNIQUE_CONSTRAINT_VIOLATION: 'JOURNAL_ENTRY.UNIQUE_CONSTRAINT_VIOLATION',
    NOT_FOUND: 'JOURNAL_ENTRY.NOT_FOUND',
    NON_POSITIVE_TOTAL: 'JOURNAL_ENTRY.NON_POSITIVE_TOTAL',
    NOT_DRAFT: 'JOURNAL_ENTRY.NOT_DRAFT',
    NOT_POSTED: 'JOURNAL_ENTRY.NOT_POSTED',
    ALREADY_REVERSED: 'JOURNAL_ENTRY.ALREADY_REVERSED',
  },
  POSTING: {
    PLATFORM_BOOKING_AMOUNTS_MISMATCH:
      'POSTING.PLATFORM_BOOKING_AMOUNTS_MISMATCH',
    PLATFORM_TENANT_NOT_CONFIGURED: 'POSTING.PLATFORM_TENANT_NOT_CONFIGURED',
    NO_PERIOD_FOR_DATE: 'POSTING.NO_PERIOD_FOR_DATE',
    PERIOD_NOT_OPEN: 'POSTING.PERIOD_NOT_OPEN',
    UNBALANCED_ENTRY: 'POSTING.UNBALANCED_ENTRY',
    ACCOUNT_NOT_POSTABLE: 'POSTING.ACCOUNT_NOT_POSTABLE',
    PARTY_REQUIRED: 'POSTING.PARTY_REQUIRED',
    ACCOUNT_CODE_NOT_FOUND: 'POSTING.ACCOUNT_CODE_NOT_FOUND',
  },
  VALIDATION: {
    FAILED: 'FAILED',
  },
  VAT: {
    NEGATIVE: 'VAT.NEGATIVE',
    INVALID_RATE: 'VAT.INVALID_RATE',
    MUST_NOT_BE_ZERO: 'VAT.MUST_NOT_BE_ZERO',
  },
  VKN: {
    INVALID_FORMAT: 'VKN.INVALID_FORMAT',
    INVALID_CHECKSUM: 'VKN.INVALID_CHECKSUM',
  },
  SUBSCRIPTION: {
    ALREADY_EXISTS: 'SUBSCRIPTION.ALREADY_EXISTS',
    NOT_FOUND: 'SUBSCRIPTION.NOT_FOUND',
    BUYER_REQUIRED: 'SUBSCRIPTION.BUYER_REQUIRED',
    CLINIC_REQUIRED: 'SUBSCRIPTION.CLINIC_REQUIRED',
    MODULE_NOT_FOUND: 'SUBSCRIPTION.MODULE_NOT_FOUND',
    MODULE_NOT_AVAILABLE: 'SUBSCRIPTION.MODULE_NOT_AVAILABLE',
    MODULE_ALREADY_ADDED: 'SUBSCRIPTION.MODULE_ALREADY_ADDED',
    MODULE_ALREADY_EXISTS: 'SUBSCRIPTION.MODULE_ALREADY_EXISTS',
    PLAN_NOT_FOUND: 'SUBSCRIPTION.PLAN_NOT_FOUND',
    MODULE_REQUIRED: 'SUBSCRIPTION.MODULE_REQUIRED',
  },
  EMPLOYEE: {
    NOT_FOUND: 'EMPLOYEE.NOT_FOUND',
    ALREADY_TERMINATED: 'EMPLOYEE.ALREADY_TERMINATED',
    CONTRACT_NOT_FOUND: 'EMPLOYEE.CONTRACT_NOT_FOUND',
    INVALID_ENTITLEMENT: 'EMPLOYEE.INVALID_ENTITLEMENT',
  },
  LEAVE: {
    NOT_FOUND: 'LEAVE.NOT_FOUND',
    INVALID_DATE_RANGE: 'LEAVE.INVALID_DATE_RANGE',
    NOT_PENDING: 'LEAVE.NOT_PENDING',
    INSUFFICIENT_BALANCE: 'LEAVE.INSUFFICIENT_BALANCE',
  },
  ATTENDANCE: {
    NOT_FOUND: 'ATTENDANCE.NOT_FOUND',
    ALREADY_RECORDED: 'ATTENDANCE.ALREADY_RECORDED',
    NOT_CHECKED_IN: 'ATTENDANCE.NOT_CHECKED_IN',
    ALREADY_CLOSED: 'ATTENDANCE.ALREADY_CLOSED',
    INVALID_TIME_RANGE: 'ATTENDANCE.INVALID_TIME_RANGE',
  },
  CONSENT_TEMPLATE: {
    NOT_FOUND: 'CONSENT_TEMPLATE.NOT_FOUND',
    ALREADY_ARCHIVED: 'CONSENT_TEMPLATE.ALREADY_ARCHIVED',
    ARCHIVED: 'CONSENT_TEMPLATE.ARCHIVED',
  },
  CONSENT_FORM: {
    NOT_FOUND: 'CONSENT_FORM.NOT_FOUND',
  },
  PURCHASE_REQUEST: {
    NOT_FOUND: 'PURCHASE_REQUEST.NOT_FOUND',
    NOT_PENDING: 'PURCHASE_REQUEST.NOT_PENDING',
    NOT_APPROVED: 'PURCHASE_REQUEST.NOT_APPROVED',
    EMPTY_ITEMS: 'PURCHASE_REQUEST.EMPTY_ITEMS',
  },
  PURCHASE_ORDER: {
    NOT_FOUND: 'PURCHASE_ORDER.NOT_FOUND',
    EMPTY_ITEMS: 'PURCHASE_ORDER.EMPTY_ITEMS',
    INVALID_STATE: 'PURCHASE_ORDER.INVALID_STATE',
    ITEM_NOT_FOUND: 'PURCHASE_ORDER.ITEM_NOT_FOUND',
    OVER_RECEIPT: 'PURCHASE_ORDER.OVER_RECEIPT',
    OVER_INVOICED: 'PURCHASE_ORDER.OVER_INVOICED',
    NOT_BILLABLE: 'PURCHASE_ORDER.NOT_BILLABLE',
    SUPPLIER_MISMATCH: 'PURCHASE_ORDER.SUPPLIER_MISMATCH',
    CURRENCY_MISMATCH: 'PURCHASE_ORDER.CURRENCY_MISMATCH',
    CLINIC_MISMATCH: 'PURCHASE_ORDER.CLINIC_MISMATCH',
  },
  PURCHASE_INVOICE: {
    NOT_FOUND: 'PURCHASE_INVOICE.NOT_FOUND',
    ALREADY_MATCHED: 'PURCHASE_INVOICE.ALREADY_MATCHED',
    NOT_MATCHED: 'PURCHASE_INVOICE.NOT_MATCHED',
    NOT_MATCHABLE: 'PURCHASE_INVOICE.NOT_MATCHABLE',
  },
  CASH_REGISTER: {
    NOT_FOUND: 'CASH_REGISTER.NOT_FOUND',
    ARCHIVED: 'CASH_REGISTER.ARCHIVED',
  },
  CASH_SESSION: {
    NOT_FOUND: 'CASH_SESSION.NOT_FOUND',
    NOT_OPEN: 'CASH_SESSION.NOT_OPEN',
    ALREADY_OPEN: 'CASH_SESSION.ALREADY_OPEN',
    INVALID_AMOUNT: 'CASH_SESSION.INVALID_AMOUNT',
  },
  BANK_ACCOUNT: {
    NOT_FOUND: 'BANK_ACCOUNT.NOT_FOUND',
    ARCHIVED: 'BANK_ACCOUNT.ARCHIVED',
  },
  BANK_STATEMENT: {
    NOT_FOUND: 'BANK_STATEMENT.NOT_FOUND',
    EMPTY_LINES: 'BANK_STATEMENT.EMPTY_LINES',
    LINE_NOT_FOUND: 'BANK_STATEMENT.LINE_NOT_FOUND',
    MATCH_REF_REQUIRED: 'BANK_STATEMENT.MATCH_REF_REQUIRED',
    MATCH_NOTE_TOO_LONG: 'BANK_STATEMENT.MATCH_NOTE_TOO_LONG',
  },
  WORK_ORDER: {
    NOT_FOUND: 'WORK_ORDER.NOT_FOUND',
    EMPTY_ITEMS: 'WORK_ORDER.EMPTY_ITEMS',
    INVALID_STATE: 'WORK_ORDER.INVALID_STATE',
    DUE_DATE_REQUIRED: 'WORK_ORDER.DUE_DATE_REQUIRED',
  },
  PROJECT: {
    NOT_FOUND: 'PROJECT.NOT_FOUND',
    INVALID_STATE: 'PROJECT.INVALID_STATE',
    CODE_TAKEN: 'PROJECT.CODE_TAKEN',
    PHASE_NOT_FOUND: 'PROJECT.PHASE_NOT_FOUND',
    PHASE_ORDER_TAKEN: 'PROJECT.PHASE_ORDER_TAKEN',
    PHASE_PROJECT_MISMATCH: 'PROJECT.PHASE_PROJECT_MISMATCH',
    TASK_NOT_FOUND: 'PROJECT.TASK_NOT_FOUND',
    TASK_INVALID_STATE: 'PROJECT.TASK_INVALID_STATE',
    COST_ALREADY_LINKED: 'PROJECT.COST_ALREADY_LINKED',
    ALLOCATION_NOT_FOUND: 'PROJECT.ALLOCATION_NOT_FOUND',
    ALLOCATION_CONFLICT: 'PROJECT.ALLOCATION_CONFLICT',
    ALLOCATION_INVALID_RANGE: 'PROJECT.ALLOCATION_INVALID_RANGE',
  },
  URL: {
    INVALID: 'URL.INVALID',
  },
} as const;

type ErrorCodeGroups = typeof ERROR_CODES;

/**
 * Tüm grupların yaprak (leaf) kod string'lerinin birleşimi:
 * 'APPOINTMENT.NOT_FOUND' | 'PAYMENT.TIMEOUT' | 'HTTP.ERROR' | ...
 * (Eski tanım grupların kendisini — `{ NOT_FOUND: ... }` — döndürüyordu; iki kademeli index gerekli.)
 */
export type ErrorCode = {
  [Group in keyof ErrorCodeGroups]: ErrorCodeGroups[Group][keyof ErrorCodeGroups[Group]];
}[keyof ErrorCodeGroups];
