import { z } from 'zod';

export const FinancialEventTypeSchema = z.enum(['SALES_INVOICE_ISSUED','SALES_INVOICE_CANCELLED','PURCHASE_INVOICE_RECEIVED','PAYMENT_RECEIVED','PAYMENT_MADE','INSTRUMENT_RECEIVED','INSTRUMENT_GIVEN','INSTRUMENT_CLEARED','STOCK_IN','STOCK_OUT','EXPENSE_RECORDED','PAYROLL_ACCRUED','DEPRECIATION','FX_REVALUATION','MANUAL_JOURNAL','OPENING_BALANCE','PERIOD_CLOSING','CASH_SESSION_CLOSED']);

export type FinancialEventTypeType = `${z.infer<typeof FinancialEventTypeSchema>}`

export default FinancialEventTypeSchema;
