export enum AuditAction {
  ORGANIZATION_CREATE = 'ORGANIZATION_CREATE',
  ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE',
  ORGANIZATION_SOFT_DELETE = 'ORGANIZATION_SOFT_DELETE',

  CLINIC_CREATE = 'CLINIC_CREATE',
  CLINIC_UPDATE = 'CLINIC_UPDATE',
  CLINIC_SOFT_DELETE = 'CLINIC_SOFT_DELETE',

  // Randevu İşlemleri
  APPOINTMENT_CREATE = 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL',

  // AI & n8n Süreçleri
  AI_PROCESS_START = 'AI_PROCESS_START',
  AI_UNCERTAIN = 'AI_UNCERTAIN', // AI ne yapılacağını anlamadı
  AI_ERROR = 'AI_ERROR',

  // Kullanıcı Hareketleri
  USER_LOGIN = 'USER_LOGIN',
  USER_REGISTER = 'USER_REGISTER',
  USER_UPDATE = 'USER_UPDATE',
  USER_REGISTER_FAILED = 'USER_REGISTER_FAILED',

  // Kritik Sistem Olayları
  DB_BACKUP = 'DB_BACKUP',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  SECURITY_VIOLATION = 'SECURITY_VIOLATION',
}

export enum AuditSource {
  WEB = 'WEB',
  MOBILE = 'MOBILE',
  N8N_AI = 'N8N_AI',
  SYSTEM = 'SYSTEM',
}
