export enum DENTAL_TREATMENT {
  DENTAL_EXAMINATION = 'DENTAL_EXAMINATION',
  SPECIALIST_DENTAL_EXAMINATION = 'SPECIALIST_DENTAL_EXAMINATION',
  PANORAMIC_XRAY = 'PANORAMIC_XRAY',

  COMPOSITE_FILLING_SINGLE_SURFACE = 'COMPOSITE_FILLING_SINGLE_SURFACE',
  COMPOSITE_FILLING_TWO_SURFACES = 'COMPOSITE_FILLING_TWO_SURFACES',

  ROOT_CANAL_TREATMENT_SINGLE_CANAL_EXCLUDING_FILLING = 'ROOT_CANAL_TREATMENT_SINGLE_CANAL_EXCLUDING_FILLING',
  ROOT_CANAL_TREATMENT_TWO_CANALS_EXCLUDING_FILLING = 'ROOT_CANAL_TREATMENT_TWO_CANALS_EXCLUDING_FILLING',

  TOOTH_EXTRACTION = 'TOOTH_EXTRACTION',
  COMPLICATED_TOOTH_EXTRACTION = 'COMPLICATED_TOOTH_EXTRACTION',
  IMPACTED_TOOTH_SURGERY = 'IMPACTED_TOOTH_SURGERY',
  DENTAL_IMPLANT_APPLICATION_SINGLE_UNIT = 'DENTAL_IMPLANT_APPLICATION_SINGLE_UNIT',

  SCALING_AND_POLISHING_SINGLE_JAW = 'SCALING_AND_POLISHING_SINGLE_JAW',
  SUBGINGIVAL_CURETTAGE_GUM_TREATMENT = 'SUBGINGIVAL_CURETTAGE_GUM_TREATMENT',

  ZIRCONIUM_CROWN_SINGLE_UNIT = 'ZIRCONIUM_CROWN_SINGLE_UNIT',
  PORCELAIN_CROWN_METAL_SUPPORTED = 'PORCELAIN_CROWN_METAL_SUPPORTED',
  FULL_DENTURE_SINGLE_JAW = 'FULL_DENTURE_SINGLE_JAW',

  TEETH_WHITENING_IN_OFFICE = 'TEETH_WHITENING_IN_OFFICE',
  PORCELAIN_LAMINATE_VENEER = 'PORCELAIN_LAMINATE_VENEER',

  FISSURE_SEALANT_SINGLE_TOOTH = 'FISSURE_SEALANT_SINGLE_TOOTH',
  FIXED_SPACE_MAINTAINER = 'FIXED_SPACE_MAINTAINER',

  BONDING_APPLICATION = 'BONDING_APPLICATION',
  DIGITAL_SMILE_DESIGN = 'DIGITAL_SMILE_DESIGN',

  SINUS_LIFTING = 'SINUS_LIFTING',
  BONE_GRAFTING = 'BONE_GRAFTING',

  CLEAR_ALIGNERS = 'CLEAR_ALIGNERS',
  NIGHT_GUARD = 'NIGHT_GUARD',

  MASSETER_BOTOX = 'MASSETER_BOTOX',
  METAL_BRACES = 'METAL_BRACES',
  PORCELAIN_BRACES = 'PORCELAIN_BRACES',
  ORTHODONTIC_CONTROL = 'ORTHODONTIC_CONTROL',
  RETAINER_APPLICATION = 'RETAINER_APPLICATION',
  LINGUAL_ORTHODONTICS = 'LINGUAL_ORTHODONTICS',

  VITALITY_TEST = 'VITALITY_TEST',
  COMPOSITE_VENEER = 'COMPOSITE_VENEER',

  INLAY_ONLAY_RESTORATION = 'INLAY_ONLAY_RESTORATION',
  FIBER_POST_APPLICATION = 'FIBER_POST_APPLICATION',

  ROOT_CANAL_RETREATMENT = 'ROOT_CANAL_RETREATMENT',
  TEETH_WHITENING_HOME_TYPE = 'TEETH_WHITENING_HOME_TYPE',

  GINGIVECTOMY_AESTHETIC = 'GINGIVECTOMY_AESTHETIC',

  COMPOSITE_VENEER_ESTHETIC = 'COMPOSITE_VENEER_ESTHETIC',
  FLUORIDE_APPLICATION_WHOLE_MOUTH = 'FLUORIDE_APPLICATION_WHOLE_MOUTH',

  REMOVABLE_SPACE_MAINTAINER = 'REMOVABLE_SPACE_MAINTAINER',

  MILK_TOOTH_AMPUTATION = 'MILK_TOOTH_AMPUTATION',

  STAINLESS_STEEL_CROWN_PEDO = 'STAINLESS_STEEL_CROWN_PEDO',

  MILK_TOOTH_EXTRACTION = 'MILK_TOOTH_EXTRACTION',

  CROWN_BRIDGE_REMOVAL = 'CROWN_BRIDGE_REMOVAL',
  PARTIAL_DENTURE_SKELETON = 'PARTIAL_DENTURE_SKELETON',
  TEMPORARY_CROWN_SINGLE_UNIT = 'TEMPORARY_CROWN_SINGLE_UNIT',
  IMPLANT_SUPPORTED_ZIRCONIUM_CROWN = 'IMPLANT_SUPPORTED_ZIRCONIUM_CROWN',

  EMAX_CROWN_SINGLE_UNIT = 'EMAX_CROWN_SINGLE_UNIT',

  APICAL_RESECTION_PER_TOOTH = 'APICAL_RESECTION_PER_TOOTH',
  FRENECTOMY_LASER_OR_SURGICAL = 'FRENECTOMY_LASER_OR_SURGICAL',
  ALVEOLOPLASTY_PER_JAW = 'ALVEOLOPLASTY_PER_JAW',
  CYST_ENUCLEATION = 'CYST_ENUCLEATION',
  ALL_ON_FOUR_SIX_SURGERY_PHASE = 'ALL_ON_FOUR_SIX_SURGERY_PHASE',

  CBCT_TOMOGRAPHY = 'CBCT_TOMOGRAPHY',
  IMPLANT_UNCOVERING_SURGERY = 'IMPLANT_UNCOVERING_SURGERY',
  HYBRID_DENTURE_ALL_ON_X = 'HYBRID_DENTURE_ALL_ON_X',
  ENDODONTIC_PALLIATIVE_TREATMENT = 'ENDODONTIC_PALLIATIVE_TREATMENT',
  FREE_GINGIVAL_GRAFT = 'FREE_GINGIVAL_GRAFT',

  ROOT_CANAL_TREATMENT_THREE_PLUS_CANALS_EXCLUDING_FILLING = 'ROOT_CANAL_TREATMENT_THREE_PLUS_CANALS_EXCLUDING_FILLING',
  PERIODONTAL_FLAP_SURGERY_PER_TOOTH = 'PERIODONTAL_FLAP_SURGERY_PER_TOOTH',
  DENTURE_REBASE_RELINE = 'DENTURE_REBASE_RELINE',
  DIGITAL_INTRAORAL_SCANNING = 'DIGITAL_INTRAORAL_SCANNING',
  COMPOSITE_FILLING_THREE_PLUS_SURFACES = 'COMPOSITE_FILLING_THREE_PLUS_SURFACES',
  POST_CORE_CAST = 'POST_CORE_CAST',
}
