export enum DENTAL_TREATMENT_CATEGORY {
  DIAGNOSIS = 'DIAGNOSIS',
  RESTORATIVE = 'RESTORATIVE',
  SURGERY = 'SURGERY',
  PEDODONTICS = 'PEDODONTICS',
  PERIODONTOLOGY = 'PERIODONTOLOGY',
  PROSTHODONTICS = 'PROSTHODONTICS',
  ORTHODONTICS = 'ORTHODONTICS',
  COSMETIC = 'COSMETIC',
  OTHER = 'OTHER',
}
